# Generated by Django 5.1 on 2024-09-23 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('image', models.URLField(blank=True, default='https://img.freepik.com/free-photo/anime-style-character-space_23-2151134190.jpg', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=14)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('hometown', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('task', models.ManyToManyField(related_name='tasks', to='Tasks.task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
