# Generated by Django 5.1 on 2024-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_remove_useraccount_task_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/anime-style-character-space_23-2151134190.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Super', 'Super'), ('Moderate', 'Moderate'), ('Below Average', 'Below Average')], max_length=20),
        ),
    ]
