# Generated by Django 5.1 on 2024-09-24 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_alter_useraccount_image_alter_useraccount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='job',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Job Holder', 'Job Holder'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.jobname'),
        ),
    ]
