# Generated by Django 5.1 on 2024-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0004_jobname_useraccount_description_useraccount_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'BD'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/cartoon-character-with-handbag-sunglasses_71767-99.jpg', null=True),
        ),
    ]
