# Generated by Django 5.1 on 2024-09-25 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0006_alter_useraccount_age_alter_useraccount_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'BD'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/androgynous-avatar-non-binary-queer-person_23-2151100207.jpg', null=True),
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_education', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('LLB', 'LLB'), ('CIVIL', 'CIVIL'), ('BBA', 'BBA'), ('OTHERS', 'OTHERS')], max_length=20, null=True)),
                ('background', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('NON-CS', 'NON-CS')], max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ssc_school', models.CharField(blank=True, max_length=30, null=True)),
                ('ssc_year', models.IntegerField(blank=True, null=True)),
                ('ssc_subject', models.CharField(blank=True, choices=[('SCIENCE', 'SCIENCE'), ('ARTS', 'ARTS'), ('COMMERCE', 'COMMERCE')], max_length=20, null=True)),
                ('hsc_school', models.CharField(blank=True, max_length=30, null=True)),
                ('hsc_year', models.IntegerField(blank=True, null=True)),
                ('hsc_subject', models.CharField(blank=True, choices=[('SCIENCE', 'SCIENCE'), ('ARTS', 'ARTS'), ('COMMERCE', 'COMMERCE')], max_length=20, null=True)),
                ('university', models.CharField(blank=True, max_length=30, null=True)),
                ('university_year', models.IntegerField(blank=True, null=True)),
                ('bootcamp', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
