# Generated by Django 5.1 on 2024-09-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0007_alter_useraccount_country_alter_useraccount_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/premium-photo/poster-anime-character-with-fiery-background_943629-32000.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='job',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Job Holder', 'Job Holder'), ('Unemployed', 'Unemployed'), ('Both', 'Both')], max_length=20, null=True),
        ),
    ]
