# Generated by Django 5.1 on 2024-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0008_useraccount_company_alter_useraccount_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/androgynous-avatar-non-binary-queer-person_23-2151100207.jpg', null=True),
        ),
    ]
